#!/bin/sh -e
# Note: the '-e' flag will make the script stop immediately upon error with 
# the error reflected in the environment.  This lets one issue commands like
# "./build sbitx && ./sbitx" to build then run if it built correctly, and not
# run if the build failed.
F=$1
O=$2
OPT=0
FLAGS="-g"
[ -z "$F" ] && {
   echo "usage:   $0 program [o]"
   echo "example: $0 sbitx"
   echo "-optional 'o' argument enables compiler optimizations"
   exit 1
}
if [ ! -z "$O" ] && [ "$O" = "o" ] ; then
	echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
	echo "!! Building optimized binary, most warnings can be safely ignored !!"
	echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
	FLAGS="-O3 -flto=auto"
	OPT=1
fi
WORKING_DIRECTORY=`pwd`
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
date
mkdir -p "./audio"
mkdir -p "./data"
mkdir -p "./web"

if test -f "data/sbitx.db"; then
	echo "database is intact"
else
	echo "database doesn't exist, it will be created"
	cd data
	sqlite3 sbitx.db < create_db.sql
	cd ..
fi

if [ "$F" != "sbitx" ]; then
  echo "compiling $F in $WORKING_DIRECTORY"
else
  VERSION=`grep VER src/sdr_ui.h | awk 'FNR==1{print $4}' | sed -e 's/"//g'`
  echo "compiling $F version $VERSION in $WORKING_DIRECTORY"
fi
gcc $FLAGS -o $F \
	 src/vfo.c src/si570.c src/sbitx_sound.c src/fft_filter.c src/sbitx_gtk.c src/sbitx_utils.c \
    src/i2cbb.c src/si5351v2.c src/ini.c src/hamlib.c src/queue.c src/modems.c src/logbook.c \
		src/modem_cw.c src/settings_ui.c src/ntputil.c \
		src/telnet.c src/macros.c src/modem_ft8.c src/remote.c src/mongoose.c src/para_eq.c src/webserver.c src/eq_ui.c src/$F.c  \
		src/ft8_lib/libft8.a  \
	-lwiringPi -lasound -lm -lfftw3 -lfftw3f -pthread -lncurses -lsqlite3 -lnsl -lrt \
	`pkg-config --cflags gtk+-3.0` `pkg-config --libs gtk+-3.0`
 
if [ $OPT -eq 1 ]; then
	#Remove debugging stuff for a smaller binary
	echo Stripping $F
	strip $F
fi


echo "Brought to you by the sBitx 64 bit project team - W9JES, W2JON, KF7YDU, and N1QM" 
echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
# This addition is used to provide the application the capability to adjust the local system time -W2JON
# It should probably always run last at it'll fail if the file system doesn't support it - N1QM
if [ "$F" = "sbitx" ] && [ -x $F ]; then 
	sudo setcap CAP_SYS_TIME+ep $F
fi
