#!/bin/sh -e
# Note: the '-e' flag will make the script stop immediately upon error with 
# the error reflected in the environment.  This makes it easier for users to
# see which command caused the error.
F=$@
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
date
cd $HOME/sbitx
git stash --include-untracked
git pull
cd $HOME/sbitx/src/ft8_lib
make
sudo make install
cd $HOME/sbitx
./build sbitx
echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"

echo "sbitx has been installed successfully. You can now close this window."
