#!/bin/sh -e
# Note: the '-e' flag will make the script stop immediately upon error with 
# the error reflected in the environment.  This makes it easier for users to
# see which command caused the error.
F=$@
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
date
cd $HOME/sbitx
git pull
cd $HOME/sbitx/ft8_lib
make
sudo make install
cd ..
./build sbitx
echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"

# Create a desktop menu shortcut
echo -e "[Desktop Entry]\nName=sBitx\nExec=sh -c 'cd $working_directory && ./sbitx'\nType=Application\nIcon=/home/pi/sbitx/sbitx_icon.png\n" | sudo tee /usr/share/applications/sbitx.desktop > /dev/null
echo -e "[Desktop Entry]\nName=sBitx Apps\nExec=sh -c 'cd $working_directory && ./sbitx'\nType=Application\nIcon=/home/pi/sbitx/sbitx_icon.png\n" | sudo tee /home/pi/Desktop/sbitx.desktop > /dev/null

# Update the menu
sudo update-desktop-database

echo "sbitx has been installed successfully. The  application has been added to the Pi menu and desktop. You can now close this window."
